version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: insecure_flask
    container_name: insecure_flask_app
    command: "bash ./runserver.sh"
    environment:
      - TITULO
      - HOST
      - DATABASE
      - DB_USER
      - DB_PASS

    expose:
      - 8080
    ports:
      - "8080:8080"

  db:
    image: postgres:14-alpine
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    expose:
      - 5432
