version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: insecure_flask
    container_name: insecure_flask_app
    command: "bash ./runserver.sh"
    environment:
      - TITULO=Mi Blog
    expose:
      - 8080
    ports:
      - "8080:8080"

  db:
    image: postgres:14-alpine
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=flask_db
      - POSTGRES_PASSWORD=pass
    expose:
      - 5432
